/**
 * @file    gpio_drv.c
 * @brief   MCAL - Digital I/O driver for NUCLEO-G431RB.
 */
#include "gpio_drv.h"
#include "main.h"   /* LED_GREEN_xxx, BTN_USER_xxx labels generated by CubeMX */

/* B1 on NUCLEO-G431RB: pressing it drives PC13 high (external pull-down).
 * Verify against UM2505 schematic; change to GPIO_PIN_RESET if active-low. */
#define BTN_ACTIVE_LEVEL    (GPIO_PIN_SET)

void GpioDrv_SetLed(bool on)
{
    HAL_GPIO_WritePin(LED_GREEN_GPIO_Port, LED_GREEN_Pin,
                      on ? GPIO_PIN_SET : GPIO_PIN_RESET);
}

void GpioDrv_ToggleLed(void)
{
    HAL_GPIO_TogglePin(LED_GREEN_GPIO_Port, LED_GREEN_Pin);
}

bool GpioDrv_IsButtonPressed(void)
{
    return (HAL_GPIO_ReadPin(BTN_USER_GPIO_Port, BTN_USER_Pin) == BTN_ACTIVE_LEVEL);
}
